"""add thunderstore and server mods

Revision ID: 2c515b093668
Revises: 0250396c39db
Create Date: 2026-02-12 11:13:35.607058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c515b093668'
down_revision: Union[str, Sequence[str], None] = '0250396c39db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_mods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dll_name', sa.String(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('mod_name', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('latest_version', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_mods_dll_name'), 'server_mods', ['dll_name'], unique=False)
    op.create_table('thunderstore_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('latest_version', sa.String(), nullable=True),
    sa.Column('package_url', sa.String(), nullable=True),
    sa.Column('download_url', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thunderstore_packages_full_name'), 'thunderstore_packages', ['full_name'], unique=False)
    op.create_index(op.f('ix_thunderstore_packages_name'), 'thunderstore_packages', ['name'], unique=False)
    op.create_index(op.f('ix_thunderstore_packages_owner'), 'thunderstore_packages', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thunderstore_packages_owner'), table_name='thunderstore_packages')
    op.drop_index(op.f('ix_thunderstore_packages_name'), table_name='thunderstore_packages')
    op.drop_index(op.f('ix_thunderstore_packages_full_name'), table_name='thunderstore_packages')
    op.drop_table('thunderstore_packages')
    op.drop_index(op.f('ix_server_mods_dll_name'), table_name='server_mods')
    op.drop_table('server_mods')
    # ### end Alembic commands ###
